print("This repo is for learning GIT")
print("This line is for git difftool")
print("Code in testing branch")
print("Temp commit")
print("Uncommited")
print("This is change made locally")
print("To check if branch new is deleted remotely")